-- IP Inventory – създаване на таблици (Oracle)
-- Изпълнение: sqlplus или SQL Developer
-- Изискване: Oracle 12c+ (за IDENTITY). За 11g използвайте sequence + trigger за id.

-- Таблица за IP pool и статус (free / reserved / assigned)
CREATE TABLE ip_pool (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip             VARCHAR2(45) NOT NULL,
    ip_type        VARCHAR2(4)  NOT NULL,
    status         VARCHAR2(10) NOT NULL DEFAULT 'free',
    service_id     VARCHAR2(255) NULL,
    reserved_at    TIMESTAMP NULL,
    assigned_at    TIMESTAMP NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ip_pool_ip UNIQUE (ip),
    CONSTRAINT chk_ip_pool_ip_type CHECK (ip_type IN ('IPv4', 'IPv6')),
    CONSTRAINT chk_ip_pool_status CHECK (status IN ('free', 'reserved', 'assigned'))
);

CREATE INDEX idx_ip_pool_service_id ON ip_pool (service_id);
CREATE INDEX idx_ip_pool_status_ip_type ON ip_pool (status, ip_type);
